### ISSUE TITLE
--matchdirs does not match full path

### ISSUE THREAD

**Issue by FloppyDisco** [Old-Man-Programmer/tree#22]
i'm making a small file explorer with `fzf`, where i am using `tree` in the preview function.
i'm sorry if this post is a bit confusing because i'll be talking about using `fzf` the tool and `fzf/` a directory on my machine, but this is how my stuff is labelled, sorry!

After reading through some of the issues here. I think my issue may be somewhat related to #17 but i figured i'd create a new issue since i am explicitly only concerned about the behavior of the `--matchdirs` flag and not the default behavior of `-P`.

In my `.scripts/` dir you can see i have a few nested directories: `fzf/`, `fzf/xplorer/`, and `fzf/xplorer/actions/`
```
.scripts/ 
  - fzf/
    - xplorer/
      - actions/
        - files...
```
<img width="1498" height="815" alt="Image" src="https://github.com/user-attachments/assets/c926e8a2-e963-4565-8b0b-47bae5341d6f" />

----------

my preview function is set to `tree --prune --matchdirs --dirsfirst --gitignore --noreport  -C -P <query>`

and with a query of `'fzf'`, we see that we get matches in `fzf` (the tool, on the right) for all files and directories contained inside the `fzf/` directory. 
`tree` displays files located in the `fzf/` directory, but we don't see `fzf/xplorer/`, `fzf/xplorer/actions/`, or any of the nested files in these dirs.
even though, technically, a query of `'fzf'` should match all of these because they all live inside the `fzf/` directory...

<img width="1498" height="815" alt="Image" src="https://github.com/user-attachments/assets/6f768fb8-98f4-47f5-abbb-911e04dc67f6" />

---------- 

now with a query of `'actions'`, there are several matches in `fzf`. (all of the files that live inside the `actions/` dir) and while `tree` is displaying the `actions/` dir it is not showing any of it's files, which should match the query. (which actually seems kind of strange that it is not pruning the directory since it is not showing any of the matching files)

<img width="1498" height="815" alt="Image" src="https://github.com/user-attachments/assets/bde024a2-14e2-4e48-bd59-8de8520bd70b" />

### so the current behavior is
 `--matchdirs` only matches files that are "in the root level directory that matches the query", and will not match on any files that are in nested directories or have a matching directory that is not the first in the path

--------------- 

the `--help` has 
```
  --matchdirs   Include directory names in -P pattern matching.
```
specifically it says `names` (plural) so my expectation would be that
`--matchdirs` would  match on ANY dir in the file path, similar to the matching in `fzf`.

just my two cents though, not saying i'm correct or anything, this is just what i expected to happen.
i also could be using this incorrectly 🤷🏻 

i believe i am on the current version
```
/opt/homebrew/bin/tree --version
tree v2.2.1 © 1996 - 2024 by Steve Baker, Thomas Moore, Francesc Rocher, Florian Sesser, Kyosuke Tokoro
```

let me know what you think, 
i can provide a few more examples if you would like, but I don't want to be any more confusing at first. 

so far this is a great tool! very much enjoying it.
thank you

**Comment by anhtr13** [comment]
> and with a query of `'fzf'`, we see that we get matches in `fzf` (the tool, on the right) for all files and directories contained inside the `fzf/` directory. `tree` displays files located in the `fzf/` directory, but we don't see `fzf/xplorer/`, `fzf/xplorer/actions/`, or any of the nested files in these dirs.

> `--matchdirs` only matches files that are "in the root level directory that matches the query", and will not match on any files that are in nested directories or have a matching directory that is not the first in the path


Hi guy, I've created a smaller version of this tool that solved your issue [here](https://github.com/anhtr13/treer), I think it's exactly what you need =]]

**Comment by Old-Man-Programmer** [comment]
I've released a new version 2.3.0 which should I hope address this issue.  Please let me know if this isn't the case.

**Comment by FloppyDisco** [comment]
hey i wasn't able to build this on mac successfully. i'm not a C guy though, so i have no idea what i'm looking at.
so i am not able to confirm for you if it is working now.
brew is still showing 2.2.1

thanks for looking into it!

**Comment by Old-Man-Programmer** [comment]
You could send me the output, or post it here.

**Comment by FloppyDisco** [comment]
<img width="2032" height="1162" alt="Image" src="https://github.com/user-attachments/assets/234a3aa4-2071-496f-b48f-c1559a28fa19" />

```
23:07:11 ❯ make
cc -O2 -Wall -fomit-frame-pointer -no-cpp-precomp  -c -o tree.o tree.c
tree.c:124:9: warning: unused variable 'stddata_fd' [-Wunused-variable]
  124 |   char *stddata_fd;
      |         ^~~~~~~~~~
tree.c:1567:53: error: no member named 'secontext' in 'struct _info'
 1567 |   if (flag.selinux) n += sprintf(buf+n, " %s", ent->secontext);
      |                                                ~~~  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/secure/_stdio.h:107:55: note: expanded from macro 'sprintf'
  107 | #define sprintf(str, ...) __sprintf_chk_func (str, 0, __VA_ARGS__)
      |                                                       ^~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/secure/_stdio.h:87:58: note: expanded from macro '__sprintf_chk_func'
   87 |         __builtin___sprintf_chk (str, flag, __darwin_obsz(str), __VA_ARGS__)
      |                                                                 ^~~~~~~~~~~
1 warning and 1 error generated.
make: *** [tree.o] Error 1

```

i uncommented the MacOS flags and commented out the linux ones.

**Comment by Old-Man-Programmer** [comment]
Well that's a problem.  Looks like I'll have to make another immediate release to fix this.  the selinux option should be completely include-guarded out of existence, but I missed something.

**Comment by Old-Man-Programmer** [comment]
If you could edit tree.c around line 1567 to look like:
```
  #ifdef __linux__
  if (flag.selinux) n += sprintf(buf+n, " %s", ent->secontext);
  #endif
```
and let me know if that is the only issue preventing compilation I would be interested in knowing.   I needed to include guard the stddata_fd as well it seems.

**Comment by FloppyDisco** [comment]
yup! that did it.

<img width="1498" height="812" alt="Image" src="https://github.com/user-attachments/assets/b12a5d0b-dea8-4adc-8acf-c3e4dce1ac79" />


and i can confirm that `2.3.0` is now returning the same output as fzf. 
it matches file names and dir names for the full path, not just in the root level

<img width="1498" height="812" alt="Image" src="https://github.com/user-attachments/assets/219bccd3-26e3-48eb-b92b-c84c7d6976fb" />
